vars:
  - method:
      name: GMPCC
      project: guidance-journal-2023
      project_folder: "../../../../../../../Documents/publications/multi-mpc-2023/results"

stages:
  run:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor

    do:
      wdir: ../../..
      cmd:
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py parameters True # Load the parameters
        - source ../../devel/setup.zsh && roslaunch lmpcc jackalsimulator.launch overwrite_pedestrian_scenario:=true pedestrian_scenario:="${item.file}" project_name:="${method.project_folder}/data"
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py restore # Load the parameters      
      deps:
        # - lmpcc/include/generated/Configuration${method.name}
        - lmpcc_tools/scripts/experiments/pedsim_benchmark_interaction/set_parameters.py
      outs:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_${method.name}.txt
  
  evaluate:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor
    do:
      wdir: ../../..
      cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 metrics.py ${item.name} ${method.name} && cd ../../../..
      deps:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_${method.name}.txt 
      metrics:
        - lmpcc_tools/scripts/data/${method.project_folder}/metrics/${item.name}/${method.name}.json 

  run-no-original:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor

    do:
      wdir: ../../..
      cmd:
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py parameters False # Load the parameters
        - source ../../devel/setup.zsh && roslaunch lmpcc jackalsimulator.launch overwrite_pedestrian_scenario:=true pedestrian_scenario:="${item.file}" project_name:="${method.project_folder}/data"
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py restore # Load the parameters      
      deps:
        - lmpcc/include/generated/Configuration${method.name}
        - lmpcc_tools/scripts/experiments/pedsim_benchmark_interaction/set_parameters.py
      outs:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_${method.name}NO.txt 
  
  evaluate-no-original:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor
    do:
      wdir: ../../..
      cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 metrics.py ${item.name} ${method.name}NO && cd ../../../..
      deps:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_${method.name}NO.txt 
      metrics:
        - lmpcc_tools/scripts/data/${method.project_folder}/metrics/${item.name}/${method.name}NO.json 

  # LMPCC (0 PATHS)
  run-lmpcc:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor

    do:
      wdir: ../../..
      cmd:
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py parameters True 0 # Load the parameters
        - source ../../devel/setup.zsh && roslaunch lmpcc jackalsimulator.launch overwrite_pedestrian_scenario:=true pedestrian_scenario:="${item.file}" project_name:="${method.project_folder}/data"
        - source ../../devel/setup.zsh && cd lmpcc_tools/scripts && python3 experiments/pedsim_benchmark_interaction/main.py restore # Load the parameters      
      deps:
        - lmpcc/include/generated/Configuration${method.name}
        - lmpcc_tools/scripts/experiments/pedsim_benchmark_interaction/set_parameters.py
      outs:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_LMPCC.txt 

  evaluate-lmpcc:
    foreach:
      unstructured:
        file: random_social/12_corridor.xml
        name: interactive_random_social-12_corridor
      medium:
        file: random_social/8_corridor.xml
        name: interactive_random_social-8_corridor
      low:
        file: random_social/4_corridor.xml
        name: interactive_random_social-4_corridor
    do:
      wdir: ../../..
      cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 metrics.py ${item.name} LMPCC && cd ../../../..
      deps:
        - lmpcc_tools/scripts/data/${method.project_folder}/data/${item.name}_LMPCC.txt 
      metrics:
        - lmpcc_tools/scripts/data/${method.project_folder}/metrics/${item.name}/LMPCC.json 

  compare:
     wdir: ../../..
     cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 compare.py -o "pedsim_interaction" -l "interactive_random_social-12_corridor" "interactive_random_social-8_corridor" "interactive_random_social-4_corridor"
     deps:
       - lmpcc_tools/scripts/compare.py
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/${method.name}.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/${method.name}NO.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/LMPCC.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/${method.name}.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/${method.name}NO.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/LMPCC.json       
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/${method.name}.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/${method.name}NO.json
       - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/LMPCC.json
     outs:
       - lmpcc_tools/scripts/data/${method.project_folder}/../latex/tables/pedsim_interaction.tex

  figures:
    wdir: ../../..
    cmd: source ~/.zshrc && cd src/lmpcc/lmpcc_tools/scripts && python3 analysis.py pedsim_interactive_boxplots
    deps:
      - lmpcc_tools/scripts/analysis.py
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/${method.name}.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/${method.name}NO.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-12_corridor/LMPCC.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/${method.name}.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/${method.name}NO.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-8_corridor/LMPCC.json       
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/${method.name}.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/${method.name}NO.json
      - lmpcc_tools/scripts/data/${method.project_folder}/metrics/interactive_random_social-4_corridor/LMPCC.json
    outs:
      - lmpcc_tools/scripts/data/${method.project_folder}/figures/pedsim_interactive_duration.pdf
      - lmpcc_tools/scripts/data/${method.project_folder}/figures/pedsim_interactive_infeasibility.pdf